### ISSUE TITLE
Bug Report: Can't apply theme via CLI

### ISSUE THREAD

**Issue by nnra6864** [Foldex/AdwSteamGtk#68]
**This issue is a problem with AdwSteamGtk and not the [Theme](https://github.com/tkashkin/Adwaita-for-Steam) it installs:**

- [x] Yes

**I have checked the [Troubleshooting](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting) page**

- [x] Yes

**Description of Issue:**

Quite simple, applying the theme via GUI or simply running running the install command works just fine, as can be seen here:
```
 I     ~/Data/Projects/Linux/Hyprland   main  adwaita-steam-gtk -i                                                                                          ✔  03:56:49 
→ Creating stage directory /tmp/tmpgdnmwox5/adwaita
→ Applying color theme ricer...
→ Applying window controls theme adwaita...
→ Applying custom css...
→ Applying window controls layout appmenu:close...
✦ Directory /home/nnra/.var/app/com.valvesoftware.Steam/.steam/steam does not exist
→ Patching Steam Client Library Files...
✓ Done!
```
But if I try passing the theme as an option it fails:
```
 I     ~/Data/Projects/Linux/Hyprland   main  adwaita-steam-gtk -i -o 'color_theme:ricer'                                                                   ✔  03:56:51 
Traceback (most recent call last):
  File "/usr/share/adwaita-steam-gtk/adwaita_steam_gtk/main.py", line 97, in do_command_line
    (code, msg) = cli.update_install(options, self.beta_support)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/adwaita-steam-gtk/adwaita_steam_gtk/cli.py", line 42, in update_install
    options = get_options(option_string)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/adwaita-steam-gtk/adwaita_steam_gtk/cli.py", line 108, in get_options
    themes_list, msg = zip.get_color_themes()
                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'adwaita_steam_gtk.zip' has no attribute 'get_color_themes'
```

**Steps to Reproduce:**
Explained in the previous section.

**[CLI Output](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting#running-in-cli):**
Already provided.

**Other Info (Screenshots, etc):**
I got it from AUR, not flatpak.

**Comment by Foldex** [comment]
Should be fixed in the next release.
The AUR build is currently out of date though, so don't know when that will be picked up.
